/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./components/**/*.{js,jsx,ts,tsx}", "./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Saira_400Regular', 'sans-serif'],
      },
      colors: {
        'on-error': 'rgb(var(--on-error))',
        'on-background': 'rgb(var(--on-background))',
        'primary-container': 'rgb(var(--primary-container))',
        'on-error-container': 'rgb(var(--on-error-container))',
        'outline': 'rgb(var(--outline))',
        'tertiary-fixed': 'rgb(var(--tertiary-fixed))',
        'on-secondary-fixed': 'rgb(var(--on-secondary-fixed))',
        'surface-container-low': 'rgb(var(--surface-container-low))',
        'on-surface': 'rgb(var(--on-surface))',
        'surface-bright': 'rgb(var(--surface-bright))',
        'secondary-container': 'rgb(var(--secondary-container))',
        'secondary-fixed': 'rgb(var(--secondary-fixed))',
        'outline-variant': 'rgb(var(--outline-variant))',
        'on-primary': 'rgb(var(--on-primary))',
        'tertiary': 'rgb(var(--tertiary))',
        'on-secondary': 'rgb(var(--on-secondary))',
        'surface': 'rgb(var(--surface))',
        'on-tertiary-fixed-variant': 'rgb(var(--on-tertiary-fixed-variant))',
        'inverse-on-surface': 'rgb(var(--inverse-on-surface))',
        'error-container': 'rgb(var(--error-container))',
        'on-tertiary': 'rgb(var(--on-tertiary))',
        'inverse-surface': 'rgb(var(--inverse-surface))',
        'on-surface-variant': 'rgb(var(--on-surface-variant))',
        'on-primary-fixed': 'rgb(var(--on-primary-fixed))',
        'error': 'rgb(var(--error))',
        'on-primary-container': 'rgb(var(--on-primary-container))',
        'surface-container-highest': 'rgb(var(--surface-container-highest))',
        'primary-fixed-dim': 'rgb(var(--primary-fixed-dim))',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest))',
        'surface-container': 'rgb(var(--surface-container))',
        'primary-fixed': 'rgb(var(--primary-fixed))',
        'surface-dim': 'rgb(var(--surface-dim))',
        'on-tertiary-fixed': 'rgb(var(--on-tertiary-fixed))',
        'on-primary-fixed-variant': 'rgb(var(--on-primary-fixed-variant))',
        'on-tertiary-container': 'rgb(var(--on-tertiary-container))',
        'surface-tint': 'rgb(var(--surface-tint))',
        'surface-variant': 'rgb(var(--surface-variant))',
        'secondary': 'rgb(var(--secondary))',
        'inverse-primary': 'rgb(var(--inverse-primary))',
        'tertiary-container': 'rgb(var(--tertiary-container))',
        'background': 'rgb(var(--background))',
        'secondary-fixed-dim': 'rgb(var(--secondary-fixed-dim))',
        'on-secondary-fixed-variant': 'rgb(var(--on-secondary-fixed-variant))',
        'surface-container-high': 'rgb(var(--surface-container-high))',
        'tertiary-fixed-dim': 'rgb(var(--tertiary-fixed-dim))',
        'primary': 'rgb(var(--primary))',
        'on-secondary-container': 'rgb(var(--on-secondary-container))',
      },
      spacing: {
        "space-3xl": "4rem",
        "max-content-width": "42rem",
        "gutter-tablet": "1.5rem",
        "margin-mobile": "1rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-xxs": "0.25rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
        "gutter-mobile": "1rem",
        "margin-tablet": "2rem",
        "space-sm": "0.75rem"
      }
    },
  },
  plugins: [],
}
